# Generated by Django 5.0.1 on 2024-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_customer_alter_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
