# Generated by Django 5.0.1 on 2024-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
