# Generated by Django 5.0.2 on 2024-04-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0008_profile_prev_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default=0, upload_to='video/%y'),
            preserve_default=False,
        ),
    ]
