# Generated by Django 5.0.2 on 2024-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_shippingaddress_shipping_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(default='', max_length=250),
        ),
    ]
